##Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

Data Collection & Pre-Processing

In [ ]:
import pandas as pd
#loading the data from csv file to a pandas Dataframe
raw_mail_data = pd.read_csv('/content/mail_data.csv')

In [ ]:
print(raw_mail_data)

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
raw_mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score

In [ ]:
raw_mail_data.isnull().sum()

Category    0
Message     0
dtype: int64

In [ ]:
# replace null values with null strings
df = raw_mail_data.where((pd.notnull(raw_mail_data)),'')

In [ ]:
# printing the first 5 rows of the dataframe
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [ ]:
# checking number of rows and columns in the dataframe
df.shape

(5572, 2)

Label Encoding

In [ ]:
# label spam mail as 0; ham mail as 1;
df.loc[df['Category'] == 'spam', 'Category',] = 0
df.loc[df['Category'] == 'ham', 'Category',] = 1

spam - 0
ham - 1

In [ ]:
from re import X
# separating the data as text and labels

X = df['Message']

Y = df['Category']

In [ ]:
print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [ ]:
print(Y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

spliting data into training and testing data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(5572,)
(4457,)
(1115,)

feature extraction

In [ ]:
# transforming the text data to feature vectors that can beused as input to the logistic regression
feature_extraction = TfidfVectorizer(min_df=1, stop_words='english', binary=True)

X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [33]:
y_train= Y_train.astype('int')
y_test= Y_test.astype('int')

In [ ]:
X_train

1978    Reply to win £100 weekly! Where will the 2006 ...
3989    Hello. Sort of out in town already. That . So ...
3935     How come guoyang go n tell her? Then u told her?
4078    Hey sathya till now we dint meet not even a si...
4086    Orange brings you ringtones from all time Char...
                              ...
3772    Hi, wlcome back, did wonder if you got eaten b...
5191                               Sorry, I'll call later
5226        Prabha..i'm soryda..realy..frm heart i'm sory
5390                           Nt joking seriously i told
860               Did he just say somebody is named tampa
Name: Message, Length: 4457, dtype: object

In [36]:
print(X_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34840 stored elements and shape (4457, 7440)>
  Coords	Values
  (0, 5512)	0.1898892037332199
  (0, 7222)	0.2173884735352799
  (0, 258)	0.2379428657041507
  (0, 7162)	0.2550284465664535
  (0, 354)	0.3544175987866074
  (0, 2724)	0.3544175987866074
  (0, 7300)	0.24288153842988894
  (0, 2049)	0.3034375179183143
  (0, 3262)	0.33791755486732394
  (0, 5800)	0.17558937755823417
  (0, 6264)	0.1898892037332199
  (0, 694)	0.3171299579602537
  (0, 2497)	0.2442158912653505
  (0, 5818)	0.22682143517864364
  (1, 3267)	0.26787130770292167
  (1, 6109)	0.32397626344658004
  (1, 6738)	0.28986069568917994
  (1, 2335)	0.21623212751660786
  (1, 5650)	0.3604441444703179
  (1, 3333)	0.20665394084233094
  (1, 2440)	0.3387054464839871
  (1, 4509)	0.40282459910606705
  (1, 3932)	0.24325511357721422
  (1, 3804)	0.19029023465152678
  (1, 2555)	0.3840709491751003
  :	:
  (4452, 3084)	0.22948428918295163
  (4452, 3290)	0.26370969643076225
  (4452, 3978)	0.4574160733416501
  (4452, 7280)	0.3968991650168732
  (4452, 2438)	0.4574160733416501
  (4452, 7264)	0.479751063610169
  (4453, 6108)	0.5975612693457145
  (4453, 4004)	0.5244851817485772
  (4453, 3874)	0.6064947019588055
  (4454, 2893)	0.38087861810984514
  (4454, 3249)	0.3182708584577292
  (4454, 5409)	0.4079234999314281
  (4454, 5149)	0.43410473161397095
  (4454, 6114)	0.4465347909835087
  (4454, 6113)	0.4465347909835087
  (4455, 6686)	0.40745931976870786
  (4455, 4660)	0.4924788339394118
  (4455, 3691)	0.5541750775894743
  (4455, 5815)	0.5332274226200294
  (4456, 3720)	0.24023610815826443
  (4456, 2236)	0.3138975170542533
  (4456, 5719)	0.32762879958318814
  (4456, 6467)	0.4816862839263015
  (4456, 6078)	0.4654515925066416
  (4456, 4518)	0.5364209818026567

In [37]:
print(X_test_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7616 stored elements and shape (1115, 7440)>
  Coords	Values
  (0, 1751)	0.34896165336060586
  (0, 2065)	0.36113324080559445
  (0, 2173)	0.30145841567028486
  (0, 3225)	0.402169324846608
  (0, 3395)	0.402169324846608
  (0, 3955)	0.3774291665065587
  (0, 4100)	0.3392428284838497
  (0, 4942)	0.27552235188443686
  (1, 1361)	0.37034060973735533
  (1, 1975)	0.3578586983359201
  (1, 3443)	0.3234324946551934
  (1, 4044)	0.3234324946551934
  (1, 5430)	0.387052012561607
  (1, 6544)	0.2204999931204713
  (1, 6642)	0.326271353777915
  (1, 6986)	0.2493471978387002
  (1, 7158)	0.3981347747267476
  (2, 1292)	0.31502044528879175
  (2, 2377)	0.42309928191578644
  (2, 3067)	0.21988546741069182
  (2, 3084)	0.21988546741069182
  (2, 3510)	0.4016985150384896
  (2, 4369)	0.42309928191578644
  (2, 5597)	0.4382833676588088
  (2, 6570)	0.30427433251497293
  :	:
  (1110, 2380)	0.3362376691126707
  (1110, 2437)	0.24437455884042017
  (1110, 2749)	0.2379337409312386
  (1110, 3084)	0.16868944269743877
  (1110, 3180)	0.3526556865484764
  (1110, 3938)	0.24167410415901527
  (1110, 4105)	0.23914254153997352
  (1110, 4497)	0.2874866271650959
  (1110, 4806)	0.26149679947415966
  (1110, 5204)	0.2537606265072484
  (1110, 6142)	0.22937745257301317
  (1110, 7076)	0.22151572349543291
  (1110, 7120)	0.20278325824090906
  (1111, 1524)	0.4325555054026121
  (1111, 2410)	0.36365496598104324
  (1111, 2425)	0.4088782922446393
  (1111, 3258)	0.45132488164412626
  (1111, 3724)	0.42134339857243075
  (1111, 7095)	0.36365496598104324
  (1112, 4351)	0.5834595274323432
  (1112, 6550)	0.6915319001748619
  (1112, 7390)	0.42586219706493245
  (1113, 1472)	0.5968782232979806
  (1113, 1600)	0.48856109936052156
  (1113, 5796)	0.6364310164851212

In [40]:
from sklearn.linear_model import LogisticRegression
model =LogisticRegression()
model.fit(X_train_features, y_train)

LogisticRegression()

In [41]:
prediction_train_data= model.predict(X_train_features)
accuracy_train_data=accuracy_score(y_train,prediction_train_data)

In [46]:
print("Accuracy on test data :", accuracy_train_data)

Accuracy on test data : 0.9649988781691721

In [43]:
prediction_test_data= model.predict(X_test_features)
accuracy_test_data=accuracy_score(y_test,prediction_test_data)

In [47]:
print("Accuracy on test data :", accuracy_test_data)

Accuracy on test data : 0.9659192825112107

Building Predictive System

In [53]:
input_user_mail = ["WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only."]
input_data_features=feature_extraction.transform(input_user_mail)

In [54]:
prediction = model.predict(input_data_features)
if prediction[0] ==1 :
  print("This is not a SPAM")
else:
  print("This is a SPAM")

This is a SPAM

In [56]:
import pickle
pickle.dump(model, open("logistic_regression.pkl", "wb"))
pickle.dump(feature_extraction, open("feature_regression.pkl", "wb"))